version: 2

jobs:
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - restore_cache:
          key: fix.sh-v1-{{ checksum "fix.sh" }}
      - run:
          name: Initialize packages
          command: './fix.sh'
      - save_cache:
          key: fix.sh-v1-{{ checksum "fix.sh" }}
          paths:
            - "/home/circleci/.pyenv"
      - run:
          name: Set up pyenv
          command: |
            export PATH="$HOME/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
      - run:
          name: Test
          command: 'tox'
          environment:
            # https://app.circleci.com/pipelines/github/apiology/cookiecutter-pypackage/4/workflows/29074dc8-944c-4600-8aaa-5116575fed90/jobs/4
            "LC_ALL": "C.UTF-8"
            "LANG": "C.UTF-8"

workflows:
  version: 2
  test:
    jobs:
      - test
